// action strings
export const ACTIONS = {
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',

    SAVE_CLIENT: "SAVE_CLIENT",
    REMOVE_CLIENT: "REMOVE_CLIENT"
}
